name: Robot Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"       # รันทุกวัน 07:00 น.ไทย (00:00 UTC)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Robot tests (headless)
        env:
          DISPLAY: ":99"
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 &
          mkdir -p tests/results
          robot -d tests/results tests

      - name: Upload Robot reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: tests/results/**
          if-no-files-found: warn

      - name: Summary
        if: always()
        run: |
          echo "## Robot Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f tests/results/output.xml ]; then
            PASSED=$(grep -o 'pass="[0-9]\+"' tests/results/output.xml | head -1 | sed 's/[^0-9]*//g')
            FAILED=$(grep -o 'fail="[0-9]\+"' tests/results/output.xml | head -1 | sed 's/[^0-9]*//g')
            echo "- Passed: $PASSED  |  Failed: $FAILED" >> $GITHUB_STEP_SUMMARY
            echo "- Report & Log อยู่ใน artifact \`robot-report\`" >> $GITHUB_STEP_SUMMARY
          fi

      # ส่งอีเมลทุกครั้งที่จบงาน (รวมเคส fail)
      - name: Send Email Report (Gmail SMTP)
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Robot CI: ${{ github.repository }} run #${{ github.run_number }} (status: ${{ job.status }})"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_USERNAME }}
          html_body: |
            <h3>Robot Framework Daily Report</h3>
            <p>Repository: <b>${{ github.repository }}</b></p>
            <p>Run #: <b>${{ github.run_number }}</b> — Status: <b>${{ job.status }}</b></p>
            <p>ดูรายละเอียดการรัน: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Action Run Link</a></p>
            <p>แนบไฟล์ผลการทดสอบไว้ให้ด้านล่าง:</p>
          attachments: |
            tests/results/report.html
            tests/results/log.html
            tests/results/output.xml
