name: Robot Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 14 * * *"   # 21:00 น.ไทย

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Robot tests (headless)
        env:
          DISPLAY: ":99"
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 &
          mkdir -p tests/results
          robot -d tests/results tests

      - name: Upload Robot reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: tests/results/**    # อัปโหลดเฉพาะโฟลเดอร์ผลลัพธ์
          if-no-files-found: warn

      - name: Summary
        if: always()
        run: |
          echo "## Robot Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f tests/results/output.xml ]; then
            PASSED=$(grep -o 'pass="[0-9]\+"' tests/results/output.xml | head -1 | sed 's/[^0-9]*//g')
            FAILED=$(grep -o 'fail="[0-9]\+"' tests/results/output.xml | head -1 | sed 's/[^0-9]*//g')
            echo "- Passed: $PASSED  |  Failed: $FAILED" >> $GITHUB_STEP_SUMMARY
            echo "- Report & Log อยู่ใน artifact \`robot-report\`" >> $GITHUB_STEP_SUMMARY
          fi
